### ISSUE TITLE
How to find active pr's

### ISSUE THREAD

**Issue by marvin-bitterlich** [teacurran/sonar-bitbucket#1]
I am trying to set this up in a ci environment. Is there a way for the plugin to automatically get pull request numbers?

**Comment by teacurran** [comment]
Sorry, Just noticed this now.

Are you using Jenkins?  If you use the Bitbucket Pull Request Builder plugin (https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin), it will set an environment variable called pullRequestId.  You can then pass this into your sonar action like: -Dsonar.bitbucket.pullRequest=${pullRequestId}
